mysite/myapp/urls.py
from django.urls import path
from . import views
from .views import check, Choice, Category

app_name = 'myapp'
urlpatterns = [
    path('test/<int:category>/', views.test, name='test'),
    path('', views.index, name='index'),
    path('check/', check, name='check')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

mysite/myapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField( max_length=20)

    def __str__(self):
        return self.name


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.text


class Choice(models.Model):
    text = models.CharField(max_length=1000)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

mysite/myapp/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render
from .models import Category, Question, Choice


def index(request):
    category = Category.objects.all()
    return render(request, 'myapp/index.html', {'category': category})


def test(request, category):
    categ1 = Category.objects.get(pk=category)
    questions = Question.objects.filter(category=categ1)
    return render(request, 'myapp/test.html', {'questions': questions})


def check(request):
    print(request.GET)
    result = ''
    for key, value in request.GET.items():
        choice = Choice.objects.get(pk=value)
        print(choice)
        result = result + f"For Question {key},answer is {choice.correct}<br>"
    return HttpResponse(result)

mysite/myapp/templates/myapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block title %}
    <title>Base Page</title>
    {% endblock %}
  </head>
  <body>
{% block navbar %}
<div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
        <h5 class="text-white h4">Collapsed content</h5>
        <span class="text-netud">Toggleable via the navbar brand.</span>
    </div>
</div>
<nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-togglar-icon"></span>
        </button>
    </div>
</nav>
{% endblock navbar %}

{% block content %}
<h1>This is base content block</h1>
{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mysite/myapp/templates/myapp/index.html
{% extends './base.html' %}

{% block title %}<title>Home page</title>{% endblock %}

{% block content %}


<div class="container-fluid">
    <div class="col" style="margin-top: 20px;">
        <div class="row row-col 1 row-cols-md-3 g-4">
            {% for category in object_list %}
            <div class="col-4">
                <div class="card h=100 text-white bg-success mb-3" style="max-width: 18rem;">
                    <div class="card-header"><h2 style="max-width: 18rem;">{{ category.name }}</h2> </div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                                <p class="addgkm aoindwponpuio awdjnpaufn9ujp8iojpaoijpio agapijgpiaojrghauprhghjpaoijgpaoirhgjpoi"></p>
                            <button style="max-width: 18rem;" onclick="location.href='{% url 'myapp:test' category.id %}'"
                                    type="button" class="btn btn-seccess">Start
                            </button>
                        </div>
                    </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

mysite/myapp/templates/myapp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container-fluid">

    <form action="{% url 'myapp:check' %}">
        {% for question in questions %}
        {{ question.text }} {{ forloop.counter }}
        <br>
    <fieldset id="{{ question.id }}">
        {% for choice in question.choice_set.all %}
        <input type="radio" id="html" name="{{ question.id }}" value="{{ choice.id }}">
        <label for="html">{{ choice.text }}</label><br>
        {% endfor %}
    </fieldset>
       <hr>
        {% endfor %}
    <input type="submit" value="OK">
    </form>
</div>

</body>
</html>